Try avoid random crash : fails
Using a separate class for threads instead of a static function.
Random crash persists.

stdout errors :
  corrupted size vs. prev_size
  double free or corruption (out)
  no error

Sample valgrind output on crash :

==169442== HEAP SUMMARY:
==169442==     in use at exit: 49,585 bytes in 826 blocks
==169442==   total heap usage: 18,517 allocs, 17,691 frees, 9,048,586 bytes allocated
==169442==
==169442== LEAK SUMMARY:
==169442==    definitely lost: 0 bytes in 0 blocks
==169442==    indirectly lost: 0 bytes in 0 blocks
==169442==      possibly lost: 0 bytes in 0 blocks
==169442==    still reachable: 49,585 bytes in 826 blocks
==169442==         suppressed: 0 bytes in 0 blocks

Sample lldb output :

error: libstdc++.so.6 {0x00181389}: DIE has DW_AT_ranges(DW_FORM_sec_offset 0x119c8) attribute, but range extraction failed (invalid range list offset 0x119c8), please file a bug and attach the file at the start of this error message
Process 170415 stopped
* thread #56, name = 'SlicerApp-real', stop reason = signal SIGSEGV: invalid address (fault address: 0xca)
    frame #0: 0x00007fffe188a797 libc.so.6`unlink_chunk.constprop.0 + 39
libc.so.6`unlink_chunk.constprop.0:
->  0x7fffe188a797 <+39>: cmpq   0x10(%rdx), %rdi
    0x7fffe188a79b <+43>: jne    0x7fffe188a800            ; <+144>
    0x7fffe188a79d <+45>: movq   %rdx, 0x18(%rax)
    0x7fffe188a7a1 <+49>: movq   %rax, 0x10(%rdx)
(lldb)