Fixed VesselnessFiltering module startup error
This error was logged because some operations were attempted before the application was fully started:

    AttributeError: 'module' object has no attribute 'vtkMRMLVolumePropertyNode'

Fixed by performing initialization steps when "startupCompleted" signal is emitted.